### ISSUE TITLE
can't be removed from rsvp group if don't join event anymore

### ISSUE THREAD

**Issue by 1moere1** [notem/Saber-Bot#2]
![image](https://user-images.githubusercontent.com/9694983/32224829-4cfe9958-be43-11e7-9ff9-4793c556c41f.png)

You can't decrement the count on a rsvp group after joining one

**Comment by notem** [comment]
If you've not yet discovered the [clear] option for schedule configuration (although I think you have), you can set it with an emoji to create a new event reaction which clears a user's RSVPs from an event.

I'll need to consider having the [clear] option setup by default. It's not immediately clear what needs to be done allow for the removal of RSVPs otherwise.

Meanwhile, I'll be closing this issue. Thanks for the report!
