### ISSUE TITLE
[Question] Reminders / Announcement print attending members

### ISSUE THREAD

**Issue by LeagueRaINi** [notem/Saber-Bot#6]
is it possible to let the bot print attending members?
"%{rsvp Yes}" only prints the number of ppl attending the event but i would like to automatically print a list of members that rsvp'ed "Yes" so i can print that in a seperate announcement channel without needing to manually call "list id"

**Comment by ItsRaisu** [comment]
A group I'm in was just looking at using this for events that we have, especially recurring events. However, we found that the reminder / announcement still used @Here on an RSVP'ed event meaning even those who Declined would be pinged.

What we were thinking was that the way it prints out @User for the "Yes" RSVP'ed part of the "!List ID" command could be used to only ping the users that RSVP'ed with a given response.

**Comment by LeagueRaINi** [comment]
`However, we found that the reminder / announcement still used @here on an RSVP'ed event meaning even those who Declined would be pinged.`
not sure what ur talking about just edit the default message?
![preview](https://i.imgur.com/ePkRPME.png)

**Comment by ItsRaisu** [comment]
Right now the options are either:
A) The reminder sends an @ for here or everyone.
B) The reminder does not send an @ at all.

What I ask, is say you have an RSVP event "Raid: Test".  User1 and User2 respond with "Yes". User3 responds with "No".

Option A)  User3 gets pinged even though he has responded that he will not be part of the event.
Option B) User1 and User2 do not get pinged as part of the reminder.

New Option, along a similar line of thinking that you posted:
> is it possible to let the bot print attending members?
> i would like to automatically print a list of members that rsvp'ed "Yes" so i can print that in a seperate announcement channel without needing to manually call "list id"

Would be to have the ability to set the Reminder/Announcement message to not just list the attending members, but to @ mention them as well so that Only those attending get pinged in the reminder.

ie: `"Event: **%t** %a -- Participants: %{@rsvp Yes}"` would (using the same example above) send the message:  `"Event: `**`Raid: Test`**` begins in 5 minutes. Participants: @User1, @User2"`

While potentially using something like "%{$rsvp Yes}" to do the same thing, listing the users that responded "Yes", without pinging them (as you originally posted about)

**Comment by ItsRaisu** [comment]
Not sure when it was put in but apparently both of these already exist as:

`%{mention Groupname}` and `%{list Groupname}`

Never saw any mention of it until Notem brought it up in the help channel on the Discord server.

**Comment by LeagueRaINi** [comment]
huh good to know i guess this can be closed then
